name: Continuous Deployment workflow

on:
    push:
        branches:
        - master

jobs:
    cd:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v2
